volumes:
  etc_wireguard:
networks:
  traefik:
    external: true
services:
  wg-easy:
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
      - LANG=tr
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=d12matrix.duckdns.org
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - 51820:51820/udp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wgeasy-frontend.rule=Host(`wgeasy.d12matrix.duckdns.org`)"
      - "traefik.http.routers.wgeasy-frontend.entrypoints=websecure"
      - "traefik.http.services.wgeasy-frontend.loadbalancer.server.port=51821"
      - "traefik.http.routers.wgeasy-frontend.service=wgeasy-frontend"