networks:
  traefik:
    external: true
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      - traefik
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      # - "80:80/tcp" 
    environment:
      TZ: 'Europe/Istanbul'
      DNSMASQ_LISTENING: all
      WEBPASSWORD: 'matrix'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.d12matrix.duckdns.org`)"
      - "traefik.http.middlewares.pihole-admin-redirect.addPrefix.prefix=/admin"
      - "traefik.http.routers.pihole.middlewares=pihole-admin-redirect"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole.service=pihole"